### PR TITLE
Vistatec/l10n checkin sleha15sp4 locdrop3

### PR DESCRIPTION
**Pull request by ptinley-vt**
### Description
This Pull Request contains the localised XML and image files for 3 ZH_CN books for SLE HA 15 SP4, locdrop3:

* Geo Clustering Guide
* NFS Quick Start
* Pacemaker Remote Quick Start

Regards,
Patrick

### CODE REVIEW

**Review by taroth21 — COMMENTED** [review]
@ptinley-vt : Many thanks! I ran a `daps optipng` and pushed the optimized PNGs. PDF and HTML versions of all guides can be built. 

However, in the PDF version of the 'Pacemaker Remote Quick Start' that I generated on my machine, the graphics on pages 2-4 are a bit hard to read because the localized string appear in black on dark green background (see attached PDF). 
[article-pacemaker-remote_color_zh_cn.pdf](https://github.com/SUSE/doc-sleha/files/9352666/article-pacemaker-remote_color_zh_cn.pdf)


In the HTML output, all strings in the same graphics are displayed in white on a dark green background and can be read without problems. 

Not sure why this happens. 

@jfaltenbacher: Can you confirm this when building the PDF locally?

@ptinley-vt : Does your reference PDF show the same issue?

I'll also ask @tomschr to have a look (just in case it is a stylesheet issue).
[article-pacemaker-remote_color_zh_cn.pdf](https://github.com/SUSE/doc-sleha/files/9352680/article-pacemaker-remote_color_zh_cn.pdf)

**Comment by jfaltenbacher** [comment]
I see the same issues for the 'Alice + Bob' images in the Pacemaker PDF guide. HTML version looks good.
No issues for the Geo clustering and NFS guide

**Comment by ptinley-vt** [comment]
> @ptinley-vt : Many thanks! I ran a `daps optipng` and pushed the optimized PNGs. PDF and HTML versions of all guides can be built.
> 
> However, in the PDF version of the 'Pacemaker Remote Quick Start' that I generated on my machine, the graphics on pages 2-4 are a bit hard to read because the localized string appear in black on dark green background (see attached PDF):
> 
> [article-pacemaker-remote_color_zh_cn.pdf](https://github.com/SUSE/doc-sleha/files/9352666/article-pacemaker-remote_color_zh_cn.pdf)
> 
> In the HTML output, all strings in the same graphics are displayed in white on a dark green background and can be read without problems.
> 
> Not sure why this happens.
> 
> @jfaltenbacher: Can you confirm this when building the PDF locally?
> 
> @ptinley-vt : Does your reference PDF show the same issue?
> 
> I'll also ask @tomschr to have a look (just in case it is a stylesheet issue).

I reported this to our artwork team and they tried tweaking the graphics at those strings. The strings are actually converted to paths so it is not a font issue. I tested the new graphics just now but unfortunately the result is the same.

**Comment by janajaeger** [comment]
@jfaltenbacher does this just concern Chinese or does this issue pop up across other translated versions as well? Also, are other images from HA affected? 
I wonder how we could tweak the SVGs to avoid issues like these in the future. en seems to build flawlessly, if I'm not mistaken. Please keep me in the loop and let me know how I can help.

**Comment by jfaltenbacher** [comment]
@janajaeger as this guide is only translated into zh-cn, we can't tell for any other language. I have created https://jira.suse.com/browse/DOCTEAM-720 and we will have a look into this issue after Tom has returned.

**Pull request merged**
