### PR TITLE
Feature/fate lvmlockd

### PR DESCRIPTION
**Pull request by taroth21**
@renzhengeek: I have (hopefully) integrated all the changes you sent - please check if the content is ok. :) 

(I also generated a PDF output of the chapter built from this feature branch, find it attached.)

After the content review, I will run the usual checks (spell check, style check etc.) before merging the feature branch to develop.  

[cha.ha.clvm_color_draft_PR#55_2018_01_30.pdf](https://github.com/SUSE/doc-sleha/files/1681457/cha.ha.clvm_color_draft_PR.55_2018_01_30.pdf)

### CODE REVIEW

**Comment by renzhengeek** [comment]
@taroth21 Tanja, thanks for your hard work! It looks good to me. After this round of change, may I bother you to mail the text version of this chapter to do another round? In the next round, I'd add more minor things, hope that will be the final round, hha

**Comment by taroth21** [comment]
@renzhengeek : No problem, thanks to you for the great input! I just sent you the text output of the latest version of the file. I will wait with the spell check, style check etc. until this feature is more or less completely documented. 
If you need further, related chapters as text output, just let me know.

**Comment by taroth21** [comment]
@renzhengeek: I would like to merge this PR tomorrow, if possible, and have run a spell check and style check (see latest commit). Please let me know if you are fine with the changes. Thanks!

**Comment by renzhengeek** [comment]
@taroth21 Tanja, thanks.  It looks good to me, except one thing:

I think it should be "OCFS2" rather than "ocfs" :)

**Comment by taroth21** [comment]
@renzhengeek  Thanks, Eric! In this case, ```&ocfs;``` is an entity which resolves to 'OCFS2' when producing the output formats (see also the attached latest draft version and the file 'entity-decl.ent', where the entities are defined, https://github.com/SUSE/doc-sleha/blob/develop/xml/entity-decl.ent). 

[cha.ha.clvm_color_draft_en.pdf](https://github.com/SUSE/doc-sleha/files/1807735/cha.ha.clvm_color_draft_en.pdf)

**Comment by renzhengeek** [comment]
Hi Tanja,

I got it, thanks! After this change, I think it is almost OK for the 
lvmlockd doc task.

Furthermore,  I talked with Gang yesterday (According to Roger, he mainly
will take over LVM's responsibility). It would be better if we can look 
more:

- add instructions about how to use "lvresize" tool when using lvmlockd;

@Gang, please look at this Trello card -
https://trello.com/c/5yBuhZQD/130-lvmlockd-verify-the-new-feature-on-sle15

in which I put the discussion thread with upstream about this.

- and maybe also "pvmove" tool instructions? It depends on how it goes 
on this bug:

  o [Bug 1080299] pvmove cannot work as expected in cluster caused by 
packaging hack

and the discussion thread with upstream and the testing result  on this 
topic, which tracked in this
Trello card:

  o https://trello.com/c/FlNFvEbZ/102-suse-lvm-use-case-pvmove

Sorry for troubles I cannot finish. Hope it goes well for you!

Regards,
Eric

**Pull request merged**
