### PR TITLE
Bugfix/upgrade paths bsc#1174719

### PR DESCRIPTION
**Pull request by taroth21**
### Description

Fix https://bugzilla.suse.com/show_bug.cgi?id=1174719 (and https://bugzilla.suse.com/show_bug.cgi?id=1139551)

### CODE REVIEW

**Comment by taroth21** [comment]
@gao-yan : Could you please have a look? I guess for the upgrade from 12 SP5 to 15 SP2, I also need to add the pointer to https://documentation.suse.com/sle-ha/15-SP2/html/SLE-HA-all/cha-ha-clvm.html#sec-ha-clvm-migrate to the table?

**Comment by gao-yan** [comment]
> @gao-yan : Could you please have a look? I guess for the upgrade from 12 SP5 to 15 SP2, I also need to add the pointer to https://documentation.suse.com/sle-ha/15-SP2/html/SLE-HA-all/cha-ha-clvm.html#sec-ha-clvm-migrate to the table?

Yes, I think so. @zzhou1 ?

**Comment by taroth21** [comment]
> > @gao-yan : Could you please have a look? I guess for the upgrade from 12 SP5 to 15 SP2, I also need to add the pointer to https://documentation.suse.com/sle-ha/15-SP2/html/SLE-HA-all/cha-ha-clvm.html#sec-ha-clvm-migrate to the table?
> 
> Yes, I think so. @zzhou1 ?

@yan-gao: Thanks for reviewing! I have added the link to the section about 'Online Migration from Mirror LV to Cluster MD' now. Plan to merge this tomorrow, after having Roger has had his say, too.

**Comment by taroth21** [comment]
Attaching the rendered PDF for easier review: [cha-ha-migration_color_en.pdf](https://github.com/SUSE/doc-sleha/files/5090991/cha-ha-migration_color_en.pdf)

**Comment by zzhou1** [comment]
> > > @gao-yan : Could you please have a look? I guess for the upgrade from 12 SP5 to 15 SP2, I also need to add the pointer to https://documentation.suse.com/sle-ha/15-SP2/html/SLE-HA-all/cha-ha-clvm.html#sec-ha-clvm-migrate to the table?
> > 
> > 
> > Yes, I think so. @zzhou1 ?
> 
> @yan-gao: Thanks for reviewing! I have added the link to the section about 'Online Migration from Mirror LV to Cluster MD' now. Plan to merge this tomorrow, after Roger has had his say, too.

Yes, it makes sense to have the link.

Sorry for the late reply. I need find a better way to manage github notifications.

**Pull request merged**
