### PR TITLE
crmsh can use non-root sudoer SSH keys

### PR DESCRIPTION
**Pull request by tahliar**
### PR creator: Description

New feature allowing you to set up the cluster and run cluster tasks as a sudo user instead of root. I'll include details of the changes in a comment.

### PR creator: Are there any relevant issues/feature requests?

* jsc#PED-2861

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [x] 15 next *(current `main`, no backport necessary)*
  - [x] 15 SP5
  - [ ] 15 SP4
  - [ ] 15 SP3
  - [ ] 15 SP2
  - [ ] 15 SP1
- SLE-HA 12
  - [ ] 12 SP5
  - [ ] 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by tahliar** [comment]
I've done a few things here: 

**1. Added the sudo option to the relevant steps in the Installation Quick Start:** 

First node:
image

Second node:
image

**2. Added a warning about remote SSH keys:**

image

**3. Added the sudo option to the existing note about the `user` option in Chapter 5.5 of the Admin Guide:** 

image

**4. Rewrote the intro to Appendix 5 of the Admin Guide:** 

image

**5. Added a note about support for SSH agent forwarding in section D3 of the same appendix:** 

image

**Comment by zzhou1** [comment]
Sounds good to me. 

NOTE: these changes are not applicable to 15SP4, and no plan yet.

**Comment by tahliar** [comment]
> Sounds good to me.
> 
> NOTE: these changes are not applicable to 15SP4, and no plan yet.

Thanks, I'll take 15SP4 off the backport list.

**Review by dariavladykina — APPROVED** [review]
LGTM!

**Pull request merged**
