### PR TITLE
Update note to mention SSH agent forwarding

### PR DESCRIPTION
**Pull request by tahliar**
### PR creator: Description

Part 1, for initial updates to quick starts for the installation media. Will include a link when I add more info to the Admin Guide.

### PR creator: Are there any relevant issues/feature requests?

* jsc#PED-7399

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [x] 15 next *(current `main`, no backport necessary)*
  - [ ] 15 SP5
  - [ ] 15 SP4
  - [ ] 15 SP3
  - [ ] 15 SP2
  - [ ] 15 SP1
- SLE-HA 12
  - [ ] 12 SP5
  - [ ] 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Review by gao-yan — APPROVED** [review]
LGTM. Thanks, @tahliar !

**Comment by tahliar** [comment]
Thanks @gao-yan!

**Comment by tahliar** [comment]
image

**Review by dariavladykina — COMMENTED** [review]
LGTM!

**Pull request merged**
