### PR TITLE
Vistatec/sle 15 hasp6 locdrop3 sleha localisation checkin

### PR DESCRIPTION
**Pull request by ptinley-vt**
### PR creator: Description

Delivering localised XML and graphics files for the SLE HA 15 SP6 **locdrop 3** books:

**SLEHA**

DC-SLE-HA-geo-clustering-guide (zh-cn)
DC-SLE-HA-nfs-storage (zh-cn)
DC-SLE-HA-pacemaker-remote (zh-cn)

3 books in total

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [ ] 15 SP6

### CODE REVIEW

**Comment by jfaltenbacher** [comment]
Thank you Patrick.

I have run:
- optipng (no files)
- validate
- visual spot check of PDFs

Only issue is that text in graphics on dark background are shown in black (white color in EN sources). I have added this to the Jira issue https://jira.suse.com/browse/DOCTEAM-1441

Files are good to be merged from my side

**Review by jfaltenbacher — APPROVED** [review]
LGTM!

**Comment by ptinley-vt** [comment]
I will take a look at this now Julia.
We had the same issue on another component (can't remember which off the top of my head) and we resolved it by not converting live text to paths.
I'll get back to you on this shortly.

**Comment by ptinley-vt** [comment]
Hi Julia,

The guy how handles the artwork localisation is on a day off today and tomorrow. I just realised, since I hadn't heard back from him. 
We can test with an updated SVG next week, if that is alright. 
Regards,
Patrick

**Comment by jfaltenbacher** [comment]
Hi Patrick, yes, that is totally fine, no worries. And thanks for taking a look into this :+1:

**Comment by taroth21** [comment]
Thanks @ptinley-vt and @jfaltenbacher ! 

I built HTML for all deliverables and did not spot anything else apart from the issues Julia already reported. The 'Edit source document' links are also gone because the respective `<dm:editurl/>` elements are located in the MAIN files and we already removed them on the locdrop 2 delivery. 

After the graphics issue is fixed (or worked around) we can merge this one.

**Review by taroth21 — CHANGES_REQUESTED** [review]
Thanks @ptinley-vt and @jfaltenbacher ! 

I built HTML for all deliverables and did not spot anything else apart from the issues Julia already reported. No need to remove the 'Edit source document' links this time because the respective `<dm:editurl/>` elements are located in the MAIN files and we had already removed them from the locdrop 2 delivery (where the MAIn was included). 

After the graphics issue is fixed (or worked around) we can merge this one.

**Comment by ptinley-vt** [comment]
We have updated and tested the problematic SVGs noted by Julia in 'article-pacemaker-remote_zh_cn.pdf' book.
They look fine now.
https://github.com/SUSE/doc-sleha/pull/412/commits/1bb237715521a591b6f3dbc96f81332c9fa97c23

**Comment by jfaltenbacher** [comment]
@ptinley-vt : thank you very much for fixing the graphics. I checked all three guides and they look good. PR can be merged from my side

**Pull request merged**
