### PR TITLE
Bugfix/offline migr bsc#1139551

### PR DESCRIPTION
**Pull request by taroth21**
### Description

Fix for bsc#1139551 - Offline migration from SLE12-SP4 to SLE15-SP1.

### Checklist
* Check all items that apply.

*Are backports required?*

- [ ] To maintenance/SLEHA12SP4
- [ ] To maintenance/SLEHA15
- [x] To maintenance/SLEHA15SP1

### CODE REVIEW

**Comment by gao-yan** [comment]
Tanja, would it make sense to similarly add the missing but probably the most interesting path for cluster offline upgrade:

From the lasted SP of the previous main release to the current, for example:

- In SLE15 SP2 doc:   SLE12 SP5 -> SLE15 SP2
- In SLE12 SP5 doc: SLE11 SP4 -> SLE12 SP5

?

**Comment by taroth21** [comment]
> @taroth21, @tomschr, could we similarly add the missing "Cluster Offline Upgrade" path for SLE15 SP2 doc? Basically the one from the latest SP of the one previous main release to the next:
> 
> SLE12 SP5 -> SLE15 SP2

@gao-yan : Thanks, will be done in https://github.com/SUSE/doc-sleha/pull/142.

**Comment by taroth21** [comment]
> > @taroth21, @tomschr, could we similarly add the missing "Cluster Offline Upgrade" path for SLE15 SP2 doc? Basically the one from the latest SP of the one previous main release to the next:
> > SLE12 SP5 -> SLE15 SP2
> 
> @gao-yan : Thanks, will be done in #142.

Fixed, see https://github.com/SUSE/doc-sleha/commit/3c398931b2fc88faeb53767783fc1f7616457f01

**Comment by gao-yan** [comment]
> > > @taroth21, @tomschr, could we similarly add the missing "Cluster Offline Upgrade" path for SLE15 SP2 doc? Basically the one from the latest SP of the one previous main release to the next:
> > > SLE12 SP5 -> SLE15 SP2
> > 
> > 
> > @gao-yan : Thanks, will be done in #142.
> 
> Fixed, see [3c39893](https://github.com/SUSE/doc-sleha/commit/3c398931b2fc88faeb53767783fc1f7616457f01)

Nicely done, thanks @taroth21 !

**Pull request merged**
