### PR TITLE
Vistatec/sle 15 sp5 locdrop2 sleha localisation checkin

### PR DESCRIPTION
**Pull request by ptinley-vt**
### PR creator: Description

SLEHA

DC-SLE-HA-administration - ja-jp zh-cn zh-tw (3)
DC-SLE-HA-geo-clustering - de-de es-es fr-fr it-it ja-jp pt-br zh-cn zh-tw (8)

11 books in total

### PR creator: Are there any relevant issues/feature requests?

no

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [x] 15 SP5

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by jfaltenbacher** [comment]
Hi Patrick, thank you very much. I have processed all books and they look good. There is a small layout issue in the PDF versions of the zh-tw admin guide and ja-jp, zh-tw geo clustering quick start but we check on our end.

**Comment by ptinley-vt** [comment]
> 

Thanks Julia.

Let me know what these layout issues are and I can check them out with the SLES/SLED component of locdrop 2.
Regards,
Patrick

**Comment by jfaltenbacher** [comment]
Hi Patrick,
The main header of the books is overlapping for the zh-tw admin guide and ja-jp, zh-tw geo clustering quick start.
I have checked the files you had uploaded to the ftp and the issue also appears there. 

The zh-tw Geo clustering is the worse:

image

**Review by taroth21 — APPROVED** [review]
Apart from the layout issue, the rest looks good - I think we can go ahead and merge

**Pull request merged**
