### PR TITLE
Remove SAP from QDevice heuristics suggestion

### PR DESCRIPTION
**Pull request by tahliar**
### PR creator: Description

Removed SAP from the QDevice heuristics suggestion, as this hasn't been tested.

### PR creator: Are there any relevant issues/feature requests?

* bsc#1228375
* jsc#DOCTEAM-1505

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [x] 15 next *(current `main`, no backport necessary)*
  - [x] 15 SP6
  - [x] 15 SP5
  - [x] 15 SP4
  - [x] 15 SP3
  - [x] 15 SP2
- SLE-HA 12
  - [ ] 12 SP5

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by tahliar** [comment]
Validates locally so there may be an issue with the check itself. @tomschr can you please investigate? 

`ERROR: Could not determine the DocBook 5 schema location by resolving "urn:x-suse:rnc:v2:geekodoc-flat" via xmlcatalog`

**Comment by tomschr** [comment]
@tahliar Thanks for the hint! :+1: 
According to the log, the container contains geekodoc Version 1.0.2.1, but the latest is version 2.3.1.1. I'll look into it. :eye:

**Comment by tomschr** [comment]
@tahliar The GH Action and the used container works again now. All green! :grin:

**Comment by tahliar** [comment]
Thanks @tomschr! :grin:

**Pull request merged**
