### PR TITLE
Vistatec/SLE 15 SP6 locdrop2 sleha localisation checkin

### PR DESCRIPTION
**Pull request by ptinley-vt**
### PR creator: Description

**SLEHA**

DC-SLE-HA-administration - ja-jp zh-cn zh-tw (3)
DC-SLE-HA-geo-clustering - de-de es-es fr-fr it-it ja-jp pt-br zh-cn zh-tw (8)
DC-SLE-HA-installation - de-de es-es fr-fr it-it ja-jp pt-br zh-cn zh-tw (8)

19 books in total

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [ ] 15 SP6

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

### CODE REVIEW

**Review by jfaltenbacher — APPROVED** [review]
All files checked and looking good.

The following checks were performed:

    optipng
    build PDF and HTML
    visual spot check
    checked for editurl but none found

Minor issues reported in https://jira.suse.com/browse/DOCTEAM-1441

Guides can be published from my side. @taroth21: would you mind cross-checking, please

**Review by taroth21 — APPROVED** [review]
Thanks @ptinley-vt and @jfaltenbacher - this one is also ready to merge now.

**Comment by PadraigDillon1** [comment]
Looking at DSC and it looks like we have a missing languages. Chinese Simplified is not appearing in the language list.

**Comment by jfaltenbacher** [comment]
@PadraigDillon1: that is on purpose. Please see comment in GitLab PR https://gitlab.suse.de/susedoc/docserv-config/-/merge_requests/968

**Pull request merged**
