### PR TITLE
Add site and location to glossary

### PR DESCRIPTION
**Pull request by tahliar**
### PR creator: Description

Added items for "site" and "location" in the glossary. I didn't include the non-constraint meaning of location, even though it's used in a few places, because it's just a regular non-technical word.

### PR creator: Are there any relevant issues/feature requests?

* jsc#DOCTEAM-108

### PR creator: Which product versions do the changes apply to?

When opening a PR, check all versions of the documentation that your PR applies to.

- SLE-HA 15
  - [x] 15 next *(current `main`, no backport necessary)*
  - [x] 15 SP5
  - [x] 15 SP4
  - [x] 15 SP3
  - [x] 15 SP2
  - [x] 15 SP1
- SLE-HA 12
  - [x] 12 SP5
  - [ ] 12 SP4

### PR reviewer only: Have all backports been applied?

The doc team member merging your PR will take care of backporting to older documents.
When opening a PR, do *not* set the following check box.

- [ ] all necessary backports are done

### CODE REVIEW

**Comment by tahliar** [comment]
Site: 

image

Location:

image

**Comment by tahliar** [comment]
@zzhou1 @gao-yan What do you think? Is this okay or have I missed some nuance?

**Review by gao-yan — APPROVED** [review]
Very nice clarifications. Thanks, @tahliar !

**Review by dariavladykina — APPROVED** [review]
LGTM.

**Pull request merged**
