### PR TITLE
Convert repo to use doc-kit for entities and common files

### PR DESCRIPTION
**Pull request by tahliar**
### Description

I converted the repo to use doc-kit, but then realised that it should wait until after loc-drop 3 so that the localised guides are all consistent, so this PR will stay in Draft form until then.

I compared diffs of the html-single build for DC-SLE-HA-all. After fixing a couple of issues, the only changes I can see now are expected ones. 

### Backports

Needs to be applied to every maintenance branch eventually, but this needs to be done very carefully, so I'll open a PR for each one as a final check. 

- [ ] To maintenance/SLEHA15SP4
- [ ] To maintenance/SLEHA15SP3
- [ ] To maintenance/SLEHA15SP2
- [ ] To maintenance/SLEHA15SP1
- [ ] To maintenance/SLEHA15
- [ ] To maintenance/SLEHA12SP5
- [ ] To maintenance/SLEHA12SP4

### CODE REVIEW

**Comment by taroth21** [comment]
@tahliar: Looks good to me! :) I think you can go ahead and merge to main already. In the long run, it makes sense to base all maintenance branches in doc-sleha on doc-kit as well (for consistency reasons). Before you tackle this for maintenance/SLEHA15SP4, it would probably be best to wait until the translations have been submitted to the l10n directory of this branch (talk to @jfaltenbacher). For the other maintenance branches, you can go ahead already. 

For doc-sle, Stefan used the `docbook5-entities-only` option (see https://github.com/SUSE/doc-sle/pull/1069). Basing all maintenance branches on doc-kit ist currently WIP for doc-sle.

**Comment by jfaltenbacher** [comment]
yes, better wait until translations are back. All files are expected back around August 16th

**Comment by tahliar** [comment]
Thanks @taroth21 and @jfaltenbacher. I think I will wait until after the translations are back, even for main, as I'd like to keep it as in-sync with the 15SP4 branch as possible.

**Comment by jfaltenbacher** [comment]
Hi @tahliar all translations are delivered  so you can go ahead and merge :)

**Comment by tahliar** [comment]
@jfaltenbacher As part of getting this ready to merge, I checked each of the book and article files to make sure they're consistent with what doc-kit creates. The commit f3d62198b0033dae27444306a0c816a59eb37581 should cover the HA item in DOCTEAM-721. Let me know if there's anything else needed :)

**Comment by jfaltenbacher** [comment]
thanks @tahliar . I checked the localized files on d.s.c. and the dates are all there now :+1:

**Pull request merged**
